name: CI
on:
   push:
      branches:
      - master
   pull_request:
      branches:
      - master
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
      -  name: Checkout
         uses: actions/checkout@v2
      -  name: Setup Node.js environment
         uses: actions/setup-node@v1.4.1
      -  name: Install ajv-cli first
         run: npm install -g ajv-cli
      -  name: Execute script
         run: sh ./scripts/validate.sh